### ISSUE TITLE
Could you give us a example for permission toggling to work in ~/.kettle/kettle.properties file? 

### ISSUE THREAD

**Issue by wowtous** [bluezio/acldash#1]
<properties>
username = ...
password = ...
</properties>

=> like this?

**Comment by agarciadom** [comment]
It's mentioned in the [config.yaml](https://github.com/bluezio/acldash/blob/master/config.yaml#L8) file. It should look like this:

```
ARTIFACTCATALOG_RESTAPI_USER=Admin
ARTIFACTCATALOG_RESTAPI_PWD=password
```

I'll check again the README.md to make sure this is mentioned :-).

**Comment by wowtous** [comment]
thx a lot.
